### ISSUE TITLE
Retrieve the git url from git metadata instead of manually  

### ISSUE THREAD

**Issue by Galileo-Galilei** [atwalsh/kac#30]
In a versioned folder, we have a .git  folder and we can use the ``git remote -vv`` command to retrieve the git url of the project's changelogautomatically . This would avoid providing it manually (as it is currently done in `kac init`).

**Comment by atwalsh** [comment]
I'd have to look into using `git` commands without some library like https://github.com/gitpython-developers/GitPython. I would not want to assume the user has `git` available where they are calling commands with `kac`, or add a dependency just for this feature.

An alternative solution might be to:
1. Check if the `.git/` folder is available in the current directory
2. Parse `.git/config`
3. Default to the first remote

**Comment by Galileo-Galilei** [comment]
I totally agree. It is a too restrictive assumption to force user to use git for using ``kac``. In fact when I wrote this issue, I assumed that the implementation would be the one you describe here.
