### ISSUE TITLE
kac bump should use the package version

### ISSUE THREAD

**Issue by Galileo-Galilei** [atwalsh/kac#31]
The current CLI prompts us to choose the new version number. This is definitely something which prevents the adoption of the tool from a CI/CD perspective: I wish I could use the command `kac bump` inside, say, a github action and either: 
- specify which version part to increment in CLi (e.g. `kac bump --type=minor`)
- Do not specify anything and use the package version inside the `__init__.py` (we should check that the version is different from the last knwon one). This will make `kac` compatible with `bump2version`.

**Comment by atwalsh** [comment]
Thank you for making this issue, in addition to #28, #29, #30! I will take a look at these and get back to you.

**Comment by atwalsh** [comment]
I like the idea of adding support for checking `__init__.py`.

Regarding CI/CD usage, I would recommend using the Changelog `bump` method directly. At a minimum, I should probably add something to the README with usage instructions/examples on how to integrate the Changelog class outside of CLI usage.

```python
from kac.changelog import Changelog
c = Changelog('CHANGELOG.md') # CHANGELOG at v0.0.1

print(c)
>>> <CHANGELOG v0.0.1>

c.bump(c.latest_version.bump_minor())
print(c)
>>> <CHANGELOG v0.1.0>
```

I'm also not opposed to adding something like the `--type` argument you suggested, although I think it should be robust enough to support bumping a major, minor, patch, pre-release, or build token. It might also be a good idea to support passing an exact version number as an argument. 

Let me know what you think.

**Comment by Galileo-Galilei** [comment]
Hi, 

first of all, thank you very much for the very quick update of the library and the support for the 2 other issues!

I've seen how to bump the changelog programatically, but for CI/CD usage I'd really like to be able to run the update from the CLI. A common workflow for me when I want to create a release looks like : 

- bump the package version number with ``bump2version``
- bump ``CHANGELOG.md``
- Create a merge request on master
- Once this MR validated, create a tag and deploy the code to PyPI.

With this setup in mind, I need to bump the Changelog from the CLI. in my mind, the bump command should:
- Check if the current version is the same one that the last release
  - if yes, raise an error: "Package version must be bumped before changelog bump"
  - If not, change the "Unreleased" section with the new version value

I think that support for ``--type`` argument is less important: since we expect the Changelog to match the package version, the first scenario should be preferred.

Passing an exact version number is breaking "keep A changelog" principles IMHO. If one claims that (s)he follows "Keep A Changelog", he *must* have a version number that bumps one part of the previous version, so he must fits in one of previous scenario.

Do you think that it makes sense?

**Comment by atwalsh** [comment]
I initially liked the idea of checking `__init__.py`, but after thinking about this more I think this change would make `kac` more dependent on the user's project (python project) instead of just being a tool for managing the CHANGELOG file. I am interested, however, in adding support for bumping without user input.

I'm thinking a `--type` or `--part` argument would work well with the options: ` [major|minor|patch|pre|build]`. I'm leaning towards `-p/--part` as the argument name. This would require me to change or remove the short option for `--pre-release` (`-p`), but I was planning on removing the short option version of this and `--build` anyways. 

Let me know what you think. Hopefully, it would still be easy for your CI/CD script to identify which argument should be passed to this new option.

**Comment by Galileo-Galilei** [comment]
Thank you very much for your commitment to take into account these suggestions! Some thoughts:

- It makes sense to make the tool python independent. If you want to be able to bump without any user input, it would likely be useful to **add a configuration file** to specify the default part to bump, or an option like "language=python" to support bumping from the package version. ``bump2version`` supports it own ``.bumpversion.cfg`` file (but it is likely a bad idea to create an extra file), but also adding a section in ``setup.cfg``. If we want to follow the most recent recommendation for python, the best place to add configuration is likely a section in the ``pyproject.toml`` file.
- I agree on the fact that ``--part`` is a much better name than ``--type`` and is consistent with ``bump2version``. Removing short options for ``--pre-release`` and ``--build`` seems fine, but it should be well documented to avoid confusing existing users workflow.
